#### *NUMPY FUNCTIONS*
#### *zeros,ones,random or many built in mathematic function*

In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
ar4=np.zeros((3,4,2,3))

In [7]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [8]:
ar4.ndim

4

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
on=np.ones((2,3,2))

In [14]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [16]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [18]:
np.empty((3,6))

array([[-0.07291667,  1.07291667,  0.        , -0.07291667,  1.07291667,
         0.2       ],
       [-0.07291667,  1.07291667,  0.4       , -0.07291667,  1.07291667,
         0.6       ],
       [-0.07291667,  1.07291667,  0.8       , -0.07291667,  1.07291667,
         1.        ]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.linspace(2,3, 20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [23]:
np.logspace(2,5 , 10 ,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [24]:
np.random.randn(3,4)

array([[ 1.70164326,  0.10776956, -0.86462969,  0.69103419],
       [ 0.62175473,  0.62267562, -0.61924026, -0.63995978],
       [-0.89086336, -0.13487061,  1.01861807,  0.29371128]])

In [25]:
arr=np.random.randn(3,4)

In [26]:
import pandas as pd

In [27]:
pd.DataFrame(arr)

          0         1         2         3
0  0.127085  1.160313 -0.514477 -0.460851
1  0.903587 -1.372884  0.375884  0.283752
2 -1.767811  1.676933 -1.169093 -0.367307

In [29]:
np.random.rand(3,4)

array([[0.49078477, 0.81005974, 0.67798099, 0.98326647],
       [0.88939384, 0.64928877, 0.5895576 , 0.01678358],
       [0.99120219, 0.33711797, 0.94005807, 0.28163563]])

In [30]:
np.random.randint(1,110,(3,4))

array([[ 19,  22,  44,  85],
       [ 51,  73,  46,  90],
       [ 17, 103,   5,  44]], dtype=int32)

In [31]:
a=np.random.randint(1,110,(3,4))

In [ ]:
pd.DataFrame(a)

    0   1   2   3
0  32  97  12  29
1   6  69  42  45
2  79  18  31  92

:

In [4]:
import pandas as pd
import numpy as np
pd.DataFrame(np.random.randint(1,110 ,(300,400))).to_csv('myfile')

In [5]:
arr=np.random.rand(3,4)

In [6]:
arr

array([[0.06044241, 0.1408546 , 0.46517659, 0.81845646],
       [0.1705209 , 0.7049998 , 0.87930708, 0.75329714],
       [0.08763271, 0.74656909, 0.64372622, 0.77990976]])

In [7]:
arr.reshape(6,2)

array([[0.06044241, 0.1408546 ],
       [0.46517659, 0.81845646],
       [0.1705209 , 0.7049998 ],
       [0.87930708, 0.75329714],
       [0.08763271, 0.74656909],
       [0.64372622, 0.77990976]])

In [11]:
arr.reshape(6,-1)

array([[0.06044241, 0.1408546 ],
       [0.46517659, 0.81845646],
       [0.1705209 , 0.7049998 ],
       [0.87930708, 0.75329714],
       [0.08763271, 0.74656909],
       [0.64372622, 0.77990976]])

In [10]:
arr1=arr.reshape(6,-1)

In [12]:
arr1

array([[0.06044241, 0.1408546 ],
       [0.46517659, 0.81845646],
       [0.1705209 , 0.7049998 ],
       [0.87930708, 0.75329714],
       [0.08763271, 0.74656909],
       [0.64372622, 0.77990976]])

In [14]:
arr1[1][1]

np.float64(0.8184564553126049)

In [15]:
arr1[0]=1200

In [16]:
arr1

array([[1.20000000e+03, 1.20000000e+03],
       [4.65176592e-01, 8.18456455e-01],
       [1.70520902e-01, 7.04999805e-01],
       [8.79307085e-01, 7.53297140e-01],
       [8.76327082e-02, 7.46569093e-01],
       [6.43726223e-01, 7.79909756e-01]])

In [17]:
arr1[2:5]

array([[0.1705209 , 0.7049998 ],
       [0.87930708, 0.75329714],
       [0.08763271, 0.74656909]])

In [18]:
arr1[2:5,1]

array([0.7049998 , 0.75329714, 0.74656909])

In [21]:
ar2=np.random.randint(1,100,(5,5))

In [22]:
ar2

array([[43,  8, 45, 32, 58],
       [36, 57, 18,  8,  9],
       [72, 16, 75, 42, 98],
       [98,  6, 21, 69, 87],
       [99, 93, 70, 54, 50]], dtype=int32)

In [26]:
ar2[ar2>50]

array([58, 57, 72, 75, 98, 98, 69, 87, 99, 93, 70, 54], dtype=int32)

In [27]:
ar2[2:4,[1,2]]

array([[16, 75],
       [ 6, 21]], dtype=int32)

In [28]:
ar2[0][0]

np.int32(43)

In [31]:
ar5=np.random.randint(1,3,(3,3))
ar6=np.random.randint(1,3,(3,3))

In [32]:
ar5

array([[1, 2, 2],
       [1, 1, 1],
       [2, 1, 1]], dtype=int32)

In [33]:
ar6

array([[1, 2, 1],
       [2, 2, 2],
       [1, 1, 2]], dtype=int32)

In [34]:
ar5+ar6

array([[2, 4, 3],
       [3, 3, 3],
       [3, 2, 3]], dtype=int32)

In [35]:
ar5-ar6

array([[ 0,  0,  1],
       [-1, -1, -1],
       [ 1,  0, -1]], dtype=int32)

In [36]:
ar5/ar6

array([[1. , 1. , 2. ],
       [0.5, 0.5, 0.5],
       [2. , 1. , 0.5]])

In [37]:
ar5*ar6

array([[1, 4, 2],
       [2, 2, 2],
       [2, 1, 2]], dtype=int32)

In [38]:
ar5@ar6

array([[7, 8, 9],
       [4, 5, 5],
       [5, 7, 6]], dtype=int32)

In [39]:
ar5/0

C:\Users\User\AppData\Local\Temp\ipykernel_17012\4261370027.py:1: RuntimeWarning: divide by zero encountered in divide
  ar5/0

array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [40]:
ar5+100

array([[101, 102, 102],
       [101, 101, 101],
       [102, 101, 101]], dtype=int32)

In [41]:
ar5**2

array([[1, 4, 4],
       [1, 1, 1],
       [4, 1, 1]], dtype=int32)

In [42]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
ar7=np.zeros((4,4))

In [44]:
row=np.array([1,2,3,4])

In [45]:
ar7+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [47]:
col=np.array([[1,2,3,4]])

In [48]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [49]:
col.T+ar7

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [51]:
ar9=np.random.randint(1,4,(3,4))

In [52]:
np.sqrt(ar9)

array([[1.41421356, 1.41421356, 1.        , 1.        ],
       [1.        , 1.41421356, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])

In [54]:
np.exp(ar9)

array([[7.3890561 , 7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [55]:
np.log10(ar9)

array([[0.30103, 0.30103, 0.     , 0.     ],
       [0.     , 0.30103, 0.     , 0.     ],
       [0.     , 0.     , 0.     , 0.     ]])